config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"pages#index"
   resources :pages, only: [:index]
   resources :menus
   get 'index2', to: 'menus#index2'
   get 'index3', to: 'menus#index3'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :genre
  has_many :comments
  has_one_attached :image


  validates :title, presence: true
  validates :money, presence: true
  validates :concept, presence: true
  validates :image, presence: true, unless: :was_attached?
  validates :genre_id, numericality: { other_than: 1 } 


  def was_attached?
    self.image.attached?
  end

end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'メニュー' },
    { id: 3, name: '期間限定' },
    { id: 4, name: 'サイド' }
  ]

  include ActiveHash::Associations
  has_many :foods

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @food1 = Food.where(genre_id: 2)
    @food1 = @food1.page(params[:page]).per(6)
    # @food2 = Food.where(genre_id: 3)
    # @food2 = @food2.page(params[:page]).per(2)
    # @food3 = Food.where(genre_id: 4)
    # @food3 = @food3.page(params[:page]).per(2)
  end

  def index2
    @food2 = Food.where(genre_id: 3)
    @food2 = @food2.page(params[:page]).per(6)
  end

  def index3
    @food3 = Food.where(genre_id: 4)
    @food3 = @food3.page(params[:page]).per(6)
  end


  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to menus_path
    else
      render :new
    end
  end

  # def show
  #   @food = Food.find(params[:id])

  # end

  def edit
    @food = Food.find(params[:id])
    # unless @prototype.user.id == current_user.id
    #   redirect_to root_path
    # end
  end

  def update
    @food = Food.find(params[:id])
    if @food.update(food_params)
      redirect_to menus_path
    else
      render :edit
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to menus_path
  end


  private

  def food_params
    params.require(:food).permit(:title, :money, :concept, :image, :genre_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!doctype html >
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>



    <title>川川うどん</title>
  </head>

  <body>
    <header>
        <div class="contents">
        </div>
            <div class="cp_fullscreenmenu">
                <input class="toggle" type="checkbox" />
                <div class="hamburger">
                <span></span></div>
                    <div class="menu"><div>
                    <ul>
                        <li><a class="dropdown-item" href="/">HOME</a></li>
                        <li><a class="dropdown-item" href="/#about">川川うどんについて</a></li>
                        <li><%= link_to "メニュー",menus_path,class:"dropdown-item" %></li>
                        <li><a class="dropdown-item" href="/#access">お店のご案内</a></li>
                        <li><a class="dropdown-item" href="/#contact">お問い合せ</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="wapper text-end">
            <div class="log-in">
                <% if user_signed_in? && current_user.id %>
                <%= button_to "ログアウト", destroy_user_session_path, method: :delete %>  
                <% else  %>
                <%= button_to "ログイン", user_session_path %>
                <%= button_to "カワちゃんここで適当に登録するんやで！", new_user_registration_path %> 
                <% end %>  
            </div>
        <div> 
        </div>
    </header>
    <%= yield %>
    <footer>
        <div class="d-flex justify-content-between py-4 my-4 border-top">
        <p class="footer text-dark bg-light">&copy; 2023 川川うどん All rights reserved.</p>
        </div>
    </footer>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        AOS.init({
            offset: 100,
            delay: 200,
            duration: 800,
            anchorPlacement:'bottom-bottom',
            once:false
        });
    </script>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with url: "/menus", model: @food, local: true do |f|%>

  <div class="field">
      <%= f.label :title, "メニュー選択" %><br />
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
  </div>
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, id:"menu_title" %>
  </div>

  <div class="field">
    <%= f.label :money, "値段" %><br />
    <%= f.text_area :money, class: :form__text, id:"udon_money" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id:"udon_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "うどんの画像" %><br />
    <%= f.file_field :image, id:"udon_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">編集ページ</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/menus/index.html.erb
  <div class="row bg-light">
    <div class="col text-center">
        <h3>メニュー一覧 </h3>
        <p>
        サイズ 小=１玉 中=２玉、大=３玉
        </p>
      <div class="row card border-dark text-primary"">
        <%= link_to "基本メニュー", menus_path,class:"col" %>  
        <%= link_to "期間限定メニュー", index2_path,class:"col" %>  
        <%= link_to "サイドメニュー", index3_path,class:"col" %>  
      </div>
      <div class="row text-center bg-light m-4">
        <h1>基本メニュー</h1>
      </div>
  </div>

  </div>
<div class="container">
  <div class="row">
        <% if user_signed_in? && current_user.id %>
          <%= link_to "メニュー投稿",new_menu_path %>
        <% end %>
  </div>

  <div class="row p-2">
  <% @food1.each do |food| %>
      <div class="col-md-4">
          <div class="card"%>
            <%= image_tag food.image %>
            <div class="card-body text-center">
            <h4 class="card-title"><%=food.title %></h4>
            <p class="card-text"><%=food.money %></p>
            <p class="card-text"><%=food.concept %></p>
                <% if user_signed_in? && current_user.id %>
                  <%= button_to "編集する", edit_menu_path(food.id),method: :get %>
                  <%= button_to "削除する", menu_path(food.id), method: :delete %>
                <% end %>
          </div>
      </div>
  </div>
  <%end%>
</div>
<%= paginate @food1 %>

app/views/menus/index2.html.erb
  <div class="row bg-light">
    <div class="col text-center">
        <h3>メニュー一覧 </h3>
        <p>
        サイズ 小=１玉 中=２玉、大=３玉
        </p>
      <div class="row card border-dark text-primary"">
        <%= link_to "基本メニュー", menus_path,class:"col" %>  
        <%= link_to "期間限定メニュー", index2_path,class:"col" %>  
        <%= link_to "サイドメニュー", index3_path,class:"col" %>  
      </div>
      <div class="row text-center bg-light m-4">
        <h1>期間限定メニュー</h1>
      </div>
  </div>
  </div>
<div class="container">
  <div class="row">
        <% if user_signed_in? && current_user.id %>
          <%= link_to "メニュー投稿",new_menu_path %>
        <% end %>
  </div>

  <div class="row">
  <% @food2.each do |food| %>
      <div class="col-md-4">
          <div class="card"%>
            <%= image_tag food.image %>
            <div class="card-body text-center">
            <h4 class="card-title"><%=food.title %></h4>
            <p class="card-text"><%=food.money %></p>
                <% if user_signed_in? && current_user.id %>
                  <%= button_to "編集する", edit_menu_path(food.id),method: :get %>
                  <%= button_to "削除する", menu_path(food.id), method: :delete %>
                <% end %>
          </div>
      </div>
  </div>
  <%end%>
</div>
<%= paginate @food2 %>

app/views/menus/index3.html.erb
  <div class="row bg-light">
    <div class="col text-center">
        <h3>メニュー一覧 </h3>
        <p>
        サイズ 小=１玉 中=２玉、大=３玉
        </p>
      <div class="row card border-dark text-primary"">
        <%= link_to "基本メニュー", menus_path,class:"col" %>  
        <%= link_to "期間限定メニュー", index2_path,class:"col" %>  
        <%= link_to "サイドメニュー", index3_path,class:"col" %>  
      </div>
      <div class="row text-center bg-light m-4">
        <h1>サイドメニュー</h1>
      </div>
  </div>
  </div>
<div class="container">
  <div class="row">
        <% if user_signed_in? && current_user.id %>
          <%= link_to "メニュー投稿",new_menu_path %>
        <% end %>
  </div>
  <div class="row">
  <% @food3.each do |food| %>
      <div class="col-md-4">
          <div class="card"%>
            <%= image_tag food.image %>
            <div class="card-body text-center">
            <h4 class="card-title"><%=food.title %></h4>
            <p class="card-text"><%=food.money %></p>
                <% if user_signed_in? && current_user.id %>
                  <%= button_to "編集する", edit_menu_path(food.id),method: :get %>
                  <%= button_to "削除する", menu_path(food.id), method: :delete %>
                <% end %>
          </div>
      </div>
  </div>
  <%end%>
</div>
<%= paginate @food3 %>

app/views/menus/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規メニュー投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <p><h3>メニュー</h3></p>
        <%= render "form" %>
    </div>
  </div>
</div>

app/views/menus/show.html.erb
<div class="show">

    <div class="foods__hedding">
            <%= @food.title %>
    </div>
      <div class="food__image">
        <%= link_to image_tag(@food.image, class: :card__img ),menu_path(@food.id) %>
          <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
          <% if user_signed_in? && current_user.id %>
            <div class="food__manage">
              <%= link_to "編集する", edit_menu_path(@food.id), class: :food__btn %>
              <%= link_to "削除する", menu_path(@food.id), method: :delete, class: :food__btn %>
          <% end %>
      </div>
</div>

app/views/pages/_about.html.erb
<div data-aos="fade-left" class="about">
 <h1 class="title-tag card border-primary text-light text-center ">川川うどんについて</h1>
  <div class="container d-flex" id="about">
      <div class="card mb-3">
        <img src="kawakawa-brothers.webp" class="card-img-top p-5" alt="card-img-top">
        <h5 class="card-title ms-4">About</h5>
        <div class="card-body">
          <p class="card-text">艶やかな美しさを持つ手打ち・手切りの麺は、独特のねじれと不ぞろいな太さが特長。口にした瞬間から驚きの食感とコシを発揮し、ちょい甘のスッキリだしと絶妙に絡んで至極の一杯へ。定番のかけやぶっかけはもちろん、自家製スパイスが決め手の「キーマカレーうどん」（500円）もリピート必至の味わいです。新たに仲間入りした和風カレーうどんや、宇多津町「くぼさんのとうふ」の油揚げが乗ったきつねうどんなど、ここでしか楽しめないうまさが満載!</p>
        </div>
      </div>
  </div>
</div>

app/views/pages/_access.html.erb
<div data-aos="fade-left" class="access">
  <h1 class="title-tag card border-primary text-light text-center">お店のご案内</h1>
  <div class="container bg-light" id="access">
      <div class="row">
        <iframe class= map, src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3298.2406159942852!2d133.78707241527957!3d34.24240338055467!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x35517d8a8509d933%3A0xa1ce1c4c9e7b55b7!2z5bed5bed44GG44Gp44KT!5e0!3m2!1sja!2sjp!4v1664271492717!5m2!1sja!2sjp" width="400" height="400" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        <h3 class="text-start">
          <p>住所</p>
          <p>〒765-0031 香川県善通寺市金蔵寺町442</p>
          <p><a href="tel:0877-55-7247">0877-55-7247</a></p>
          <p>営業時間</p>
          <p>11:00～14:00 (麵がなくなり次第終了)</p>
        <p> ※休みは火曜日、水曜日 </p>
        </h3>
      </div>
  </div>
</div>

app/views/pages/_contact.html.erb
<div data-aos="fade-right" class="contact">
  <h1 class="title-tag card border-primary text-light text-center">お問い合わせ</h1>
  <div class="container bg-light" id="contact">
    <div class="row">
      <table class="table full-width" >
        <tbody>
          <tr>
            <th><label for="name">お名前</label></th>
            <td><input class="full-width" type="text" name="お名前" placeholder="名前を記入" id="exampNameInput"></td>
          </tr>
          <tr>
            <th><label for="email">メールアドレス</label></th>
            <td><input class="full-width" type="email" name="Email" placeholder="メールアドレスを記入" id="exampleEmailInput"></td>
          </tr>
          <tr>
            <th><label for="tel">お電話番号</label></th>
            <td><input class="full-width" type="tel" name="お電話番号" placeholder="お電話番号を記入" id="exampleTellInput"></td>
          </tr>
          <tr>
            <th><label for="exampleMessage">お問い合わせ内容</label></th>
            <td><textarea class="full-width textarea" name="お問い合わせ内容" placeholder="用件をご記入ください …" id="exampleMessage"></textarea></td>
          </tr>
        </tbody>
      </table>
      <p class="center"><input class="button" type="submit" value="送 信"></p>
  </div>
</div>

app/views/pages/_menu.html.erb
<div data-aos="fade-right" class="menur">
  <h1 class="title-tag card border-primary text-light text-center">メニュー</h1><br> 
  <div class="container bg-light"id="menu">
    <div class="row gx-5">
        <%= link_to "おしながき",menus_path,class:"menu-button h2" %>
        <div class="col">
          <div class="p-3 border bg-light"> <img src="ki-ma-curry.JPG" class="img-thumbnail" alt="img-thumbnail"></div>
        </div>
        <div class="col">
          <div class="p-3 border bg-light">  <img src="bukkake.JPG" class="img-thumbnail" alt="img-thumbnail"></div>
        </div>
        <%= link_to "一覧",menus_path,class:"menu-button h2" %>
    </div>
    </div>
  </div>
</div>

app/views/pages/_top-page.html.erb
<div class="top-image">
    <!-- intervalの設定 -->
    <div id="carouselExample" class="carousel slide" data-bs-ride="carousel" data-bs-interval="15000">
        <ol class="carousel-indicators">
            <li data-bs-target="#carouselExample" data-bs-slide-to="0" class="active"></li>
            <li data-bs-target="#carouselExample" data-bs-slide-to="1"></li>
        </ol>
        <!-- カルーセル部分 -->
        <div class="carousel-inner">
            <!-- First slide -->
            <div class="carousel-item active">
                <img class="d-block w-100" src="kawakawa-gaikan.jpeg" alt="川川外観の写真">
                <div class="carousel-caption">
                    <h3>大きな看板が目印</h3>
                    <p>ぜひお越しください!!</p>
                </div>
            </div>
            <!-- Second slide -->
            <div class="carousel-item">
                <img class="d-block w-100" src="bukkake.JPG" alt="ぶっかけうどんの写真">
                <div class="carousel-caption">
                    <h3>ぶっかけうどん</h3>
                    <p>当店の一押しです</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="bg-light text-dark">
            <ul class="list-unstyled p-2 ms-5">
                <h5><li>営業時間</li></h5>
                <h6>11:00~14:00<br>※休みは火曜日、水曜日</h6>
                <li>玉切れ・臨時休業の場合あり。</li>
                <li>柔らかめの細麺。茹で置きしないため提供にお時間がかかります。ご了承ください。</li>
                <li>食器の返却や天ぷらがセルフです。</li>
                <li>各メニューなくなり次第終了です</li>
            </ul>
        </div>
    </div>
</div>

app/views/pages/index.html.erb
<%=render "top-page"%>
<%=render "news"%>
<%=render "about"%>
<%=render "menu"%>
<%=render "access"%>
<%=render "contact"%>